[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_vault = "GUbN5S329CeH435tMB6ogzqGXgxzaKZxoJWaXm6pWvKh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/matthewpfeifer/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
